source = $HOME/.config/hypr/config/monitor.conf
source = $HOME/.config/hypr/config/programs.conf
source = $HOME/.config/hypr/config/autostart.conf
source = $HOME/.config/hypr/config/env.conf
source = $HOME/.config/hypr/config/permissions.conf
source = $HOME/.config/hypr/config/keybindings.conf
source = $HOME/.config/hypr/config/windowrules.conf
source = $HOME/.config/hypr/config/animations.conf 
source = $HOME/.config/hypr/config/variables/decorations.conf
source = $HOME/.config/hypr/config/variables/device.conf
source = $HOME/.config/hypr/config/variables/dwindle.conf
source = $HOME/.config/hypr/config/variables/general.conf
source = $HOME/.config/hypr/config/variables/gesture.conf
source = $HOME/.config/hypr/config/variables/input.conf
source = $HOME/.config/hypr/config/variables/master.conf
source = $HOME/.config/hypr/config/variables/misc.conf
