#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = waybar
exec-once = hyprpaper
exec-once = clipse -listen
exec-once = ~/.config/hypr/scripts/xdg-desktop-sharing.sh
exec-once = systemctl --user start hyprpolkitagent
exec-once = waybar-module-pomodoro
